export const GET_INVENTORY_REPORT_PERSISTENCE = Symbol(
  'GET_INVENTORY_REPORT_PERSISTENCE',
);
export const GET_SALES_REPORT_PERSISTENCE = Symbol(
  'GET_SALES_REPORT_PERSISTENCE',
);
export const GET_MARGIN_REPORT_PERSISTENCE = Symbol(
  'GET_MARGIN_REPORT_PERSISTENCE',
);
export const GET_EXPIRATION_REPORT_PERSISTENCE = Symbol(
  'GET_EXPIRATION_REPORT_PERSISTENCE',
);
