[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate --schema apps/backend/prisma/schema.prisma && npm run build --workspace @gestao-pedidos/backend"

[deploy]
startCommand = "npx prisma migrate deploy --schema apps/backend/prisma/schema.prisma && npm run start --workspace @gestao-pedidos/backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
