export const CREATE_API_KEY_PERSISTENCE = Symbol('CREATE_API_KEY_PERSISTENCE');
export const REVOKE_API_KEY_PERSISTENCE = Symbol('REVOKE_API_KEY_PERSISTENCE');
export const LIST_API_KEYS_PERSISTENCE = Symbol('LIST_API_KEYS_PERSISTENCE');
export const API_KEY_HASH_SERVICE = Symbol('API_KEY_HASH_SERVICE');
export const IMPORT_NFE_PERSISTENCE = Symbol('IMPORT_NFE_PERSISTENCE');
export const APPROVE_IMPORTED_ORDER_PERSISTENCE = Symbol(
  'APPROVE_IMPORTED_ORDER_PERSISTENCE',
);
export const REJECT_IMPORTED_ORDER_PERSISTENCE = Symbol(
  'REJECT_IMPORTED_ORDER_PERSISTENCE',
);
