export const ADJUST_STOCK_PERSISTENCE = Symbol('ADJUST_STOCK_PERSISTENCE');
export const GET_CURRENT_STOCK_PERSISTENCE = Symbol(
  'GET_CURRENT_STOCK_PERSISTENCE',
);
export const LIST_INVENTORY_MOVEMENTS_PERSISTENCE = Symbol(
  'LIST_INVENTORY_MOVEMENTS_PERSISTENCE',
);
