export const CREATE_SALE_PERSISTENCE = Symbol('CREATE_SALE_PERSISTENCE');
export const CANCEL_SALE_PERSISTENCE = Symbol('CANCEL_SALE_PERSISTENCE');
export const SALE_RECEIPT_GENERATOR = Symbol('SALE_RECEIPT_GENERATOR');
export const SALE_RECEIPT_PERSISTENCE = Symbol('SALE_RECEIPT_PERSISTENCE');
export const LIST_SALES_PERSISTENCE = Symbol('LIST_SALES_PERSISTENCE');
