export const CREATE_BRAND_PERSISTENCE = Symbol('CREATE_BRAND_PERSISTENCE');
export const UPDATE_BRAND_PERSISTENCE = Symbol('UPDATE_BRAND_PERSISTENCE');
export const SET_BRAND_ACTIVE_PERSISTENCE = Symbol(
  'SET_BRAND_ACTIVE_PERSISTENCE',
);
