export const CANCEL_ORDER_PERSISTENCE = Symbol('CANCEL_ORDER_PERSISTENCE');
export const CREATE_ORDER_PERSISTENCE = Symbol('CREATE_ORDER_PERSISTENCE');
export const GET_ORDER_PERSISTENCE = Symbol('GET_ORDER_PERSISTENCE');
export const LIST_ORDERS_PERSISTENCE = Symbol('LIST_ORDERS_PERSISTENCE');
export const RECEIVE_ORDER_PERSISTENCE = Symbol('RECEIVE_ORDER_PERSISTENCE');
export const UPDATE_ORDER_PERSISTENCE = Symbol('UPDATE_ORDER_PERSISTENCE');
