export const CREATE_PRODUCT_PERSISTENCE = Symbol('CREATE_PRODUCT_PERSISTENCE');
export const GET_PRODUCT_PERSISTENCE = Symbol('GET_PRODUCT_PERSISTENCE');
export const SET_PRODUCT_ACTIVE_PERSISTENCE = Symbol(
  'SET_PRODUCT_ACTIVE_PERSISTENCE',
);
export const UPDATE_PRODUCT_PERSISTENCE = Symbol('UPDATE_PRODUCT_PERSISTENCE');
