export const CREATE_CUSTOMER_PERSISTENCE = Symbol(
  'CREATE_CUSTOMER_PERSISTENCE',
);
export const GET_CUSTOMER_PERSISTENCE = Symbol('GET_CUSTOMER_PERSISTENCE');
export const LIST_CUSTOMERS_PERSISTENCE = Symbol(
  'LIST_CUSTOMERS_PERSISTENCE',
);
export const UPDATE_CUSTOMER_PERSISTENCE = Symbol(
  'UPDATE_CUSTOMER_PERSISTENCE',
);
