export const CREATE_CATEGORY_PERSISTENCE = Symbol(
  'CREATE_CATEGORY_PERSISTENCE',
);
export const UPDATE_CATEGORY_PERSISTENCE = Symbol(
  'UPDATE_CATEGORY_PERSISTENCE',
);
export const SET_CATEGORY_ACTIVE_PERSISTENCE = Symbol(
  'SET_CATEGORY_ACTIVE_PERSISTENCE',
);
